modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Layers-of-Railways/Railway/issues"
license="MIT"
[[mods]]
    modId="railways"
    version="${file.jarVersion}"
    displayName="Create: Steam 'n Rails"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails"
    logoFile="logo.png"
    authors="The Railways Team"
    description='''Customization and extension of Create rail systems and steam system
    Features include:
        Custom track types for all vanilla woods
        Conductors that can operate redstone and carry toolboxes
        and more to come...'''

[[dependencies.railways]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.railways]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, 1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.railways]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.e,)"
    ordering="AFTER"
    side="BOTH"
