name: Build Forge Release

on:
  workflow_dispatch:
    inputs:
      create_forge_version:
        description: Create forge dependency version
        required: true

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    env:
      ITHUNDXRMAVENUSERNAME: ${{ secrets.ITHUNDXRMAVENUSERNAME }}
      ITHUNDXRMAVENPASSWORD: ${{ secrets.ITHUNDXRMAVENPASSWORD }}
      CREATE_FORGE_VER: ${{ github.event.inputs.create_forge_version }}
      RELEASE_BUILD: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build Forge
        run: ./gradlew :forge:build

      - name: show folder
        run: ls build/libs/

#      - name: Upload Mod to Modrinth
#        run: ./gradlew :forge:modrinth
#
#      - name: Upload Mod to Curseforge
#        run: ./gradlew :forge:publishCurseForge